### ISSUE TITLE
老哥已star,小米报错,着急抢许嵩回流票,帮忙看看

### ISSUE THREAD

**Issue by CHEN-Jing194** [DracoYan-111/damai_grab_votes#16]
➜ python .\damai_app.py
Traceback (most recent call last):
  File "D:\code\zaluan\damai_grab_votes\damai_appium\damai_app.py", line 42, in <module>
    driver = webdriver.Remote(config.server_url, options=device_app_info)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\appium\webdriver\webdriver.py", line 229, in __init__
    super().__init__(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\appium\webdriver\webdriver.py", line 320, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\downloads\\Compressed\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s a9629a2b shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Command output:
Exception occurred while executing 'delete':
java.lang.SecurityException: Permission denial, must have one of: [android.permission.WRITE_SECURE_SETTINGS]
        at com.android.providers.settings.SettingsProvider.enforceHasAtLeastOnePermission(SettingsProvider.java:2359)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1494)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1486)
        at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1457)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:544)
        at android.content.ContentProvider.call(ContentProvider.java:2700)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:634)
        at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:408)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:282)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:50)
        at android.os.Binder.shellCommand(Binder.java:1075)
        at android.os.Binder.onTransact(Binder.java:895)
        at android.os.Binder.execTransactInternal(Binder.java:1351)
        at android.os.Binder.execTransact(Binder.java:1282)

Exception occurred while executing 'delete':
java.lang.SecurityException: Permission denial, must have one of: [android.permission.WRITE_SECURE_SETTINGS]
        at com.android.providers.settings.SettingsProvider.enforceHasAtLeastOnePermission(SettingsProvider.java:2359)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1494)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1486)
        at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1457)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:544)
        at android.content.ContentProvider.call(ContentProvider.java:2700)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:634)
        at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:408)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:282)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:50)
        at android.os.Binder.shellCommand(Binder.java:1075)
        at android.os.Binder.onTransact(Binder.java:895)
        at android.os.Binder.execTransactInternal(Binder.java:1351)
        at android.os.Binder.execTransact(Binder.java:1282)

Exception occurred while executing 'delete':
java.lang.SecurityException: Permission denial, must have one of: [android.permission.WRITE_SECURE_SETTINGS]
        at com.android.providers.settings.SettingsProvider.enforceHasAtLeastOnePermission(SettingsProvider.java:2359)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1494)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1486)
        at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1457)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:544)
        at android.content.ContentProvider.call(ContentProvider.java:2700)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:634)
        at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:408)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:282)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:50)
        at android.os.Binder.shellCommand(Binder.java:1075)
        at android.os.Binder.onTransact(Binder.java:895)
        at android.os.Binder.execTransactInternal(Binder.java:1351)
        at android.os.Binder.execTransact(Binder.java:1282)

Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\downloads\\Compressed\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s a9629a2b shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Command output:
Exception occurred while executing 'delete':
java.lang.SecurityException: Permission denial, must have one of: [android.permission.WRITE_SECURE_SETTINGS]
        at com.android.providers.settings.SettingsProvider.enforceHasAtLeastOnePermission(SettingsProvider.java:2359)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1494)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1486)
        at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1457)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:544)
        at android.content.ContentProvider.call(ContentProvider.java:2700)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:634)
        at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:408)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:282)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:50)
        at android.os.Binder.shellCommand(Binder.java:1075)
        at android.os.Binder.onTransact(Binder.java:895)
        at android.os.Binder.execTransactInternal(Binder.java:1351)
        at android.os.Binder.execTransact(Binder.java:1282)

Exception occurred while executing 'delete':
java.lang.SecurityException: Permission denial, must have one of: [android.permission.WRITE_SECURE_SETTINGS]
        at com.android.providers.settings.SettingsProvider.enforceHasAtLeastOnePermission(SettingsProvider.java:2359)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1494)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1486)
        at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1457)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:544)
        at android.content.ContentProvider.call(ContentProvider.java:2700)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:634)
        at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:408)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:282)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:50)
        at android.os.Binder.shellCommand(Binder.java:1075)
        at android.os.Binder.onTransact(Binder.java:895)
        at android.os.Binder.execTransactInternal(Binder.java:1351)
        at android.os.Binder.execTransact(Binder.java:1282)

Exception occurred while executing 'delete':
java.lang.SecurityException: Permission denial, must have one of: [android.permission.WRITE_SECURE_SETTINGS]
        at com.android.providers.settings.SettingsProvider.enforceHasAtLeastOnePermission(SettingsProvider.java:2359)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1494)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1486)
        at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1457)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:544)
        at android.content.ContentProvider.call(ContentProvider.java:2700)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:634)
        at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:408)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:282)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:50)
        at android.os.Binder.shellCommand(Binder.java:1075)
        at android.os.Binder.onTransact(Binder.java:895)
        at android.os.Binder.execTransactInternal(Binder.java:1351)
        at android.os.Binder.execTransact(Binder.java:1282)

    at getResponseForW3CError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1118:9)
    at asyncHandler (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:491:57)

**Comment by CHEN-Jing194** [comment]
![image](https://github.com/DracoYan-111/damai_grab_votes/assets/49305655/5c9bf106-fab1-4f9b-9ecf-2e423a25a263)
有查到开这个有用 但是好像小米没这个选项

**Comment by CHEN-Jing194** [comment]
![image](https://github.com/DracoYan-111/damai_grab_votes/assets/49305655/39f7d336-15f9-4280-87e9-673759422f75)
好像是这个东西 但是打开了依旧是同样的报错

**Comment by DracoYan-111** [comment]
太扯了 小米 遥遥领先 问题太多了，关键我也没见过呀哥😂

**Comment by CHEN-Jing194** [comment]
老哥 我跑起来了  抢票的逻辑我改了下  处理了一些特殊情况   应该更健壮了些  但是由于代码格式化工具不一样  导致代码看起来像都改了一样  你看看我要不要试着提个PR

**Comment by DracoYan-111** [comment]
牛逼大佬，提！提大块的！

**Comment by CHEN-Jing194** [comment]
已经提了 可以看看有什么问题没有哈哈

**Comment by xianyi5413** [comment]
大佬！求助一下，我也是想去看许嵩的www

**Comment by CHEN-Jing194** [comment]
> 大佬！求助一下，我也是想去看许嵩的www

朋友 这种太火的感觉没太大用  关键是会弹验证码 那个有点没办法现在

**Comment by vvandk** [comment]
大佬能不能加一个联系方式，有偿探讨一下，我的vx：k2445667550

**Comment by CHEN-Jing194** [comment]
> 大佬能不能加一个联系方式，有偿探讨一下，我的vx：k2445667550

没事  有啥问题直接说吧  知无不言😂

**Comment by fj0203** [comment]
> 老哥 我跑起来了 抢票的逻辑我改了下 处理了一些特殊情况 应该更健壮了些 但是由于代码格式化工具不一样 导致代码看起来像都改了一样 你看看我要不要试着提个PR

有新方法，vx18955603474，可以交流

**Comment by fj0203** [comment]
> > 大佬！求助一下，我也是想去看许嵩的www
> 
> 朋友 这种太火的感觉没太大用 关键是会弹验证码 那个有点没办法现在

有新方法，vx18955603474，可以交流
