### ISSUE TITLE
有没有大佬帮我看看，运行以后提示我没有selenium,但是我安装了selenium

### ISSUE THREAD

**Issue by evilovelin** [DracoYan-111/damai_grab_votes#23]
D:\dm\pythonProject\.venv\Scripts\python.exe E:\Desktop\123\damai.py 
Traceback (most recent call last):
  File "E:\Desktop\123\damai.py", line 11, in <module>
    from concert import Concert
  File "E:\Desktop\123\concert.py", line 14, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

Process finished with exit code 1
这是错误代码

**Comment by DracoYan-111** [comment]
应该是selenium没装到你自己的本地环境，尽管你运行了pip

**Comment by Leslieice** [comment]
大佬有没有ios端的啊
