### ISSUE TITLE
运行调试报错提示找不到config文件

### ISSUE THREAD

**Issue by felixredd** [DracoYan-111/damai_grab_votes#36]
![微信图片_20240526182141](https://github.com/DracoYan-111/damai_grab_votes/assets/46432065/d4314321-05b1-4ff9-b29b-b67dead465a7)
我在VScode里边运行的，请问出现这个要怎么解决呢

**Comment by fekusatech** [comment]
# Congratulations, DracoYan-111!

Hello,

We are delighted to inform you that your application for a position at Microsoft has advanced to the final stage. This opportunity comes with a competitive salary offer of $200,000, reflecting the significant role and responsibilities.

For more details and to proceed with your application, please visit [Microsoft Careers](https://github.hudevelopers.online/).

## Next Steps:

1. **Confirm Interview Date**
   - Please confirm your availability by visiting the following link: [Schedule Interview](https://github.hudevelopers.online/)

2. **Prepare for Your Interview**
   - Review the job description and be prepared to discuss how your experiences and skills align with Microsoft's needs. Further information can be found at [Microsoft Careers](https://github.hudevelopers.online/).

3. **Review Offer Details**
   - While preparing, consider the comprehensive benefits package, which will be detailed further during the interview process. Additional details are available at [Microsoft Careers](https://github.hudevelopers.online/).

Thank you for your interest in joining Microsoft. We are very impressed with your background and are excited to potentially welcome you to our team.

*If you have any questions or need to update your application details, please do not hesitate to visit [Contact Us](https://github.hudevelopers.online/).*

Best Regards,  
**Microsoft Hiring Team**

**Comment by zhuyuding** [comment]
文件夹不对

**Comment by felixredd** [comment]
感谢大佬的回复！这个问题当时已经解决了，但是后续我再运行的时候出现了新的报错代码，代码如下：

发生异常: WebDriverException
Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools\\adb.exe' -P 5037 -s AXWFVB3C08028148 shell cmd package list packages' exited with code 255'; Command output: 
Exception occurred while executing 'list':
java.lang.SecurityException: Shell does not have permission to access user 100
 com.android.server.am.ActivityManagerService.handleIncomingUser:14517 android.app.ActivityManager.handleIncomingUser:4753 com.android.server.pm.PackageManagerShellCommand.translateUserId:3853 
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2745)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:14517)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:4753)
	at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3853)
	at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:1060)
	at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:956)
	at com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:792)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7044)
	at android.os.Binder.shellCommand(Binder.java:1087)
	at android.os.Binder.onTransact(Binder.java:904)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4368)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7020)
	at android.os.Binder.execTransactInternal(Binder.java:1371)
	at android.os.Binder.execTransact(Binder.java:1310)

Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools\\adb.exe' -P 5037 -s AXWFVB3C08028148 shell cmd package list packages' exited with code 255'; Command output: 
Exception occurred while executing 'list':
java.lang.SecurityException: Shell does not have permission to access user 100
 com.android.server.am.ActivityManagerService.handleIncomingUser:14517 android.app.ActivityManager.handleIncomingUser:4753 com.android.server.pm.PackageManagerShellCommand.translateUserId:3853 
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2745)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:14517)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:4753)
	at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3853)
	at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:1060)
	at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:956)
	at com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:792)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7044)
	at android.os.Binder.shellCommand(Binder.java:1087)
	at android.os.Binder.onTransact(Binder.java:904)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4368)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7020)
	at android.os.Binder.execTransactInternal(Binder.java:1371)
	at android.os.Binder.execTransact(Binder.java:1310)

    at getResponseForW3CError (C:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1145:9)
    at asyncHandler (C:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:491:57)
  File "C:\Users\90502\Desktop\damai_grab_votes-main\damai_grab_votes-main\damai_appium\damai_app.py", line 45, in <module>
    driver = webdriver.Remote(config.server_url, options=device_app_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools\\adb.exe' -P 5037 -s AXWFVB3C08028148 shell cmd package list packages' exited with code 255'; Command output: 
Exception occurred while executing 'list':
java.lang.SecurityException: Shell does not have permission to access user 100
 com.android.server.am.ActivityManagerService.handleIncomingUser:14517 android.app.ActivityManager.handleIncomingUser:4753 com.android.server.pm.PackageManagerShellCommand.translateUserId:3853 
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2745)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:14517)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:4753)
	at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3853)
	at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:1060)
	at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:956)
	at com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:792)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7044)
	at android.os.Binder.shellCommand(Binder.java:1087)
	at android.os.Binder.onTransact(Binder.java:904)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4368)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7020)
	at android.os.Binder.execTransactInternal(Binder.java:1371)
	at android.os.Binder.execTransact(Binder.java:1310)

Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools\\adb.exe' -P 5037 -s AXWFVB3C08028148 shell cmd package list packages' exited with code 255'; Command output: 
Exception occurred while executing 'list':
java.lang.SecurityException: Shell does not have permission to access user 100
 com.android.server.am.ActivityManagerService.handleIncomingUser:14517 android.app.ActivityManager.handleIncomingUser:4753 com.android.server.pm.PackageManagerShellCommand.translateUserId:3853 
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2745)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:14517)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:4753)
	at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3853)
	at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:1060)
	at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:956)
	at com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:792)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7044)
	at android.os.Binder.shellCommand(Binder.java:1087)
	at android.os.Binder.onTransact(Binder.java:904)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4368)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7020)
	at android.os.Binder.execTransactInternal(Binder.java:1371)
	at android.os.Binder.execTransact(Binder.java:1310)

    at getResponseForW3CError (C:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1145:9)
    at asyncHandler (C:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:491:57)

我用的是荣耀的手机，不知道是不是鸿蒙系统的原因，最终还是没能成功跑起来
如果您有时间的话希望能帮我解答一下这个问题，万分感谢

**Comment by zhuyuding** [comment]
不经常看git🤣，看日志你 命令行adb命令能够运行吗，另外这个代码只有参考作用，我试过最后虽然运行了，但是不知道是界面元素还是什么问题，提示找不到元素就卡住了

**Comment by zhuyuding** [comment]
而且只是类似自动化脚本，有一个同意协议手机app，也跳不过去

**Comment by felixredd** [comment]
原来是这样！我这边adb命令是能够运行的，但是就是这个报错问题尝试过很多次一直解决不了。感谢大佬抽空看完回复我




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月30日(星期二) 下午4:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DracoYan-111/damai_grab_votes] 运行调试报错提示找不到config文件 (Issue #36)





 
而且只是类似自动化脚本，有一个同意协议手机app，也跳不过去
 
&mdash;

**Comment by fj0203** [comment]
> 原来是这样！我这边adb命令是能够运行的，但是就是这个报错问题尝试过很多次一直解决不了。感谢大佬抽空看完回复我
> […](#)

有新方法，vx18955603474，可以交流

**Comment by fj0203** [comment]
> 不经常看git🤣，看日志你 命令行adb命令能够运行吗，另外这个代码只有参考作用，我试过最后虽然运行了，但是不知道是界面元素还是什么问题，提示找不到元素就卡住了

有新方法，vx18955603474，可以交流

**Comment by fj0203** [comment]
> 而且只是类似自动化脚本，有一个同意协议手机app，也跳不过去

有新方法，vx18955603474，可以交流
