### ISSUE TITLE
控件id好像换名称了，运行出错

### ISSUE THREAD

**Issue by Zprestonx** [DracoYan-111/damai_grab_votes#37]
Traceback (most recent call last):
  File "F:\damai\damai_grab_votes-main\damai_appium\damai_app.py", line 55, in <module>
    driver.find_element(by=By.ID, value='cn.damai:id/channel_search_text').click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python3\Lib\site-packages\appium\webdriver\webdriver.py", line 382, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python3\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "F:\python3\Lib\site-packages\appium\webdriver\errorhandler.py", line 125, in check_response
    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (C:\Users\86575\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.ts:86:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\Users\86575\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:60:12)
    at AndroidUiautomator2Driver.findElement (C:\Users\86575\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:75:12)

**Comment by fj0203** [comment]
> Traceback (most recent call last): File "F:\damai\damai_grab_votes-main\damai_appium\damai_app.py", line 55, in driver.find_element(by=By.ID, value='cn.damai:id/channel_search_text').click() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\python3\Lib\site-packages\appium\webdriver\webdriver.py", line 382, in find_element return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value'] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\python3\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute self.error_handler.check_response(response) File "F:\python3\Lib\site-packages\appium\webdriver\errorhandler.py", line 125, in check_response raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace)) selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception Stacktrace: NoSuchElementError: An element could not be located on the page using the given search parameters. at AndroidUiautomator2Driver.findElOrEls (C:\Users\86575.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.ts:86:11) at processTicksAndRejections (node:internal/process/task_queues:95:5) at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\Users\86575\AppData\Roaming\npm\node_modules\appium\node_modules@appium\base-driver\lib\basedriver\commands\find.ts:60:12) at AndroidUiautomator2Driver.findElement (C:\Users\86575\AppData\Roaming\npm\node_modules\appium\node_modules@appium\base-driver\lib\basedriver\commands\find.ts:75:12)

vx18955603474，可以交流
